
NAMES = {
'DAG-and-IP3-signaling':'DAG/IP3',
'ERK1-ERK2-pathway':'ERK1/ERK2',
'FasL--CD95L-signaling':'FasL/CD95L',
'Integrin-signaling':'Integrin',
'MAPK6-MAPK4-signaling':'MAPK4/MAPK6',
'mTOR-signalling':'mTOR',
'p75-NTR-receptor-mediated-signalling':'NTR',
'PI3K-AKT-Signaling':'PI3K/AKT',
'Signaling-by-Activin':'Activin',
'Signaling-by-BMP':'BMP',
'Signaling-by-EGFR':'EGFR',
'Signaling-by-ERBB2':'ERBB2',
'Signaling-by-ERBB4':'ERBB4',
'Signaling-by-FGFR':'FGFR',
'Signaling-by-GPCR':'GPCR',
'Signaling-by-Hedgehog':'Hedgehog',
'Signaling-by-Hippo':'Hippo',
'Signaling-by-Insulin-receptor':'Insulin',
'Signaling-by-Leptin':'Leptin',
'Signaling-by-MET':'MET',
'Signaling-by-MST1':'MST1',
'Signaling-by-NOTCH':'Notch',
'Signaling-by-NTRKs':'NTRKs',
'Signaling-by-Nuclear-Receptors':'Nuclear',
'Signaling-by-PDGF':'PDGF',
'Signaling-by-PTK6':'PTK6',
'Signaling-by-Rho-GTPases':'Rho GTPases',
'Signaling-by-SCF-KIT':'SCF-KIT',
'Signaling-by-TGF-beta-Receptor-Complex':'TGFB',
'Signaling-by-Type-1-Insulin-like-Growth-Factor-1-Receptor-(IGF1R)':'IGF1R',
'Signaling-by-VEGF':'VEGF',
'Signaling-by-WNT':'Wnt',
'TNF-signaling':'TNF',
'TRAIL-signaling':'TRAIL'
}

## old sorting
'''
sorted_pathways = ['Signaling-by-EGFR', 'Signaling-by-ERBB2', 'Signaling-by-ERBB4', 'Signaling-by-SCF-KIT', 
'Signaling-by-FGFR', 'ERK1-ERK2-pathway','Signaling-by-GPCR','Signaling-by-PDGF', 
'Signaling-by-VEGF',  'DAG-and-IP3-signaling', 
'Signaling-by-NTRKs',  'PI3K-AKT-Signaling', 'Signaling-by-WNT', 
'Integrin-signaling',
'Signaling-by-MET', 'Signaling-by-Type-1-Insulin-like-Growth-Factor-1-Receptor-(IGF1R)', 
'Signaling-by-Insulin-receptor', 
'TNF-signaling', #'TRAIL-signaling',  'FasL--CD95L-signaling', 
'Signaling-by-Activin', 'Signaling-by-TGF-beta-Receptor-Complex', 'Signaling-by-NOTCH', 'Signaling-by-PTK6', 
'Signaling-by-Rho-GTPases',  'MAPK6-MAPK4-signaling', 
 'p75-NTR-receptor-mediated-signalling', 'Signaling-by-MST1',
'mTOR-signalling', 'Signaling-by-Hedgehog',
'Signaling-by-Nuclear-Receptors', 'Signaling-by-Leptin', 'Signaling-by-BMP', 'Signaling-by-Hippo']
'''

## new sorting
sorted_pathways = [
'Signaling-by-EGFR',
'Signaling-by-ERBB2',
'Signaling-by-ERBB4',
'PI3K-AKT-Signaling',
'Signaling-by-MET',
'Signaling-by-FGFR',
'ERK1-ERK2-pathway',
'Signaling-by-Type-1-Insulin-like-Growth-Factor-1-Receptor-(IGF1R)', 
'Signaling-by-Insulin-receptor', 
'Integrin-signaling',
'Signaling-by-GPCR',
'DAG-and-IP3-signaling',
'Signaling-by-PDGF', 
'Signaling-by-VEGF', 
'Signaling-by-NTRKs',
'Signaling-by-WNT', 
'TNF-signaling', 
'Signaling-by-PTK6',   
'Signaling-by-TGF-beta-Receptor-Complex', 
'TRAIL-signaling',
'FasL--CD95L-signaling',
'Signaling-by-NOTCH', 
'Signaling-by-BMP', 
'Signaling-by-Activin', 
 'MAPK6-MAPK4-signaling', 
'p75-NTR-receptor-mediated-signalling', 
'Signaling-by-SCF-KIT',
'Signaling-by-Hedgehog',
'Signaling-by-Nuclear-Receptors', 
'Signaling-by-Leptin', 
'Signaling-by-Hippo',
'Signaling-by-Rho-GTPases',
'Signaling-by-MST1',
'mTOR-signalling']
